# Generated by Django 5.1.11 on 2025-08-20 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_alter_movie_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('script', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('acting', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('soundtrack', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('overalscore', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
