# Generated by Django 5.1.11 on 2025-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_birth_date'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movie_list',
            field=models.ManyToManyField(related_name='profiles', to='movies.movie'),
        ),
    ]
