# Generated by Django 5.2.5 on 2025-08-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_movie_list'),
        ('movies', '0004_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie'),
        ),
    ]
