# Generated by Django 5.2.5 on 2025-08-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_selected_club'),
        ('clubs', '0005_club_next_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.club'),
        ),
    ]
