# Generated by Django 5.1.11 on 2025-08-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_alter_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
                ('past_movies', models.ManyToManyField(blank=True, related_name='past_clubs', to='movies.movie')),
                ('vote_movies', models.ManyToManyField(blank=True, related_name='voted_clubs', to='movies.movie')),
            ],
        ),
    ]
