# Generated by Django 5.1.11 on 2025-08-20 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
