# Generated by Django 5.1.11 on 2025-08-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='next_discussion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
