# Generated by Django 5.2.5 on 2025-08-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_next_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='next_discussion',
            new_name='next_pick',
        ),
    ]
