# Generated by Django 5.1.11 on 2025-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.CharField(max_length=10)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('imdb_votes', models.CharField(max_length=20)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('movie_type', models.CharField(max_length=20)),
                ('dvd', models.CharField(max_length=10)),
                ('box_office', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('response', models.BooleanField(default=True)),
                ('ratings', models.ManyToManyField(related_name='movies', to='movies.rating')),
            ],
        ),
    ]
